// Code generated by mockery v2.26.1. DO NOT EDIT.
// TODO: Regenerate mocks with updated API

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// PClient is an autogenerated mock type for the PClient type
type PClient struct {
	mock.Mock
}

// Placeholder to fix compilation
// TODO: Regenerate proper mocks when API is stable