{
 "title": "Machine Metrics",
 "description": "CPU, disk, memory, etc.",
 "tags": [ "Lux" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "machine", "query": { "query": "label_values(instance)" } },
   { "name": "host", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$machine\", job=~\"luxd-machine\", mode=\"idle\"}[1m])) by (instance)) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Machine Network I/O",
   "type": "timeseries",
   "description": "Include I/O from applications other than Luxd",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$machine\"}[5m])",
     "legendFormat": "Receive {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$machine\"}[5m])",
     "legendFormat": "Transmit {{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "Includes I/O from applications other than Luxd",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$machine\"}[5m])",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$machine\"}[5m])",
     "legendFormat": "Write {{device}}"
    }
   ]
  },
  {
   "title": "Memory Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes{instance=~\"$machine\",job=~\"luxd-machine\"} - node_memory_MemFree_bytes{instance=~\"$machine\",job=~\"luxd-machine\"} - node_memory_Buffers_bytes{instance=~\"$machine\",job=~\"luxd-machine\"} - node_memory_Cached_bytes{instance=~\"$machine\",job=~\"luxd-machine\"}) / node_memory_MemTotal_bytes{instance=~\"$machine\",job=~\"luxd-machine\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Disk Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(((node_filesystem_size_bytes{instance=~\"$machine\",job=~\"luxd-machine\", fstype=~\"ext4|vfat\"} - node_filesystem_free_bytes{instance=~\"$machine\",job=~\"luxd-machine\", fstype=~\"ext4|vfat\"}) / node_filesystem_size_bytes{instance=~\"$machine\",job=~\"luxd-machine\", fstype=~\"ext4|vfat\"}) * 100) by (instance)",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Number of Go goroutines",
   "type": "timeseries",
   "description": "Number of parallel execution threads in the client runtime",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "lux_go_goroutines{instance=~\"$host\",job=~\"luxd\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "Number of Open Files",
   "type": "timeseries",
   "description": "Number of open file handles the client is keeping",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "lux_process_open_fds{instance=~\"$host\",job=~\"luxd\"}",
     "legendFormat": "Open files"
    },
    {
     "expr": "lux_process_max_fds{instance=~\"$host\",job=~\"luxd\"}",
     "legendFormat": "Max number allowed"
    }
   ]
  }
 ]
}