{
 "title": "X-Chain",
 "tags": [ "Lux" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Blocks Accepted/Rejected in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(lux_X_blks_accepted_count{instance=~\"$host\",job=\"luxd\"}[1m]))>0",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "Block Acceptance Latency",
   "type": "timeseries",
   "description": "The average time between a block's issuance and acceptance by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(lux_X_blks_accepted_sum{instance=~\"$host\",job=\"luxd\"}[5m]) / rate(lux_X_blks_accepted_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "Accepted"
    },
    {
     "expr": "rate(lux_X_blks_rejected_sum{instance=~\"$host\",job=\"luxd\"}[5m]) / rate(lux_X_blks_rejected_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Blocks Processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lux_X_blks_processing{instance=~\"$host\", job=\"luxd\"}>0",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Percentage of Successful Queries",
   "type": "timeseries",
   "description": "Percentage of queries sent that we receive a response to. (Average over the last 5 minutes.)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(increase(lux_X_handler_chits_count{instance=~\"$host\",job=\"luxd\"}[5m]) + 1) / (increase(lux_X_handler_chits_count{instance=~\"$host\",job=\"luxd\"}[5m]) + increase(lux_X_handler_query_failed_count{instance=~\"$host\",job=\"luxd\"}[5m]) + 1)",
     "legendFormat": "% Successful"
    }
   ]
  },
  {
   "title": "Message Handling Time (Total)",
   "type": "timeseries",
   "description": "Measures how much of each second is being spent handling different kinds of messages on the X-Chain.\nThe value for chits, for example, is the number of seconds spent handling chits messages per second.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(lux_X_handler_pull_query_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(lux_X_handler_push_query_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(lux_X_handler_chits_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(lux_X_handler_accepted_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(lux_X_handler_get_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(lux_X_handler_put_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(lux_X_handler_multiput_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(lux_X_handler_get_ancestors_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(lux_X_handler_get_failed_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(lux_X_handler_query_failed_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(lux_X_handler_get_accepted_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(lux_X_handler_get_ancestors_failed_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(lux_X_handler_app_request_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(lux_X_handler_app_request_failed_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "app request failed"
    },
    {
     "expr": "rate(lux_X_handler_app_response_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "app response"
    },
    {
     "expr": "rate(lux_X_handler_app_gossip_sum{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "app gossip"
    }
   ]
  },
  {
   "title": "Message Handling Time",
   "type": "timeseries",
   "description": "Measures how long each kind of request on the X-Chain takes to handle.\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(lux_X_handler_pull_query_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_pull_query_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(lux_X_handler_push_query_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_push_query_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(lux_X_handler_chits_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_chits_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(lux_X_handler_accepted_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_accepted_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(lux_X_handler_get_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_get_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(lux_X_handler_put_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_put_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(lux_X_handler_multiput_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_multi_put_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(lux_X_handler_get_ancestors_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_get_ancestors_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(lux_X_handler_get_failed_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_get_failed_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(lux_X_handler_query_failed_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_query_failed_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(lux_X_handler_get_accepted_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_get_accepted_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(lux_X_handler_get_ancestors_failed_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_get_ancestors_failed_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(lux_X_handler_app_request_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_app_request_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(lux_X_handler_app_request_failed_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_app_request_failed_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "app request failed"
    },
    {
     "expr": "rate(lux_X_handler_app_gossip_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_app_gossip_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(lux_X_handler_app_response_sum{instance=~\"$host\",job=\"luxd\"}[5m])/rate(lux_X_handler_app_response_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "LUX Benched",
   "type": "timeseries",
   "description": "The total stake of validators currently \"benched\" due to poor query responsiveness. Queries to these validators will immediately timeout until they are removed from the \"bench.\"",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(lux_X_benchlist_benched_weight{instance=~\"$host\",job=\"luxd\"}[15m]) / 10^9",
     "legendFormat": "LUX Benched"
    }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "timeseries",
   "description": "Measures how many of each kind of message are received per second on the X-Chain.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lux_X_handler_pull_query_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(lux_X_handler_push_query_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(lux_X_handler_chits_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(lux_X_handler_accepted_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(lux_X_handler_get_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(lux_X_handler_put_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(lux_X_handler_multi_put_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(lux_X_handler_get_ancestors_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(lux_X_handler_get_failed_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(lux_X_handler_query_failed_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(lux_X_handler_get_accepted_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(lux_X_handler_get_ancestors_failed_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(lux_X_handler_chits_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(lux_X_handler_app_request_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(lux_X_handler_app_request_failed_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "app request failed"
    },
    {
     "expr": "rate(lux_X_handler_app_response_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "app response"
    },
    {
     "expr": "rate(lux_X_handler_app_gossip_count{instance=~\"$host\",job=\"luxd\"}[5m])",
     "legendFormat": "app gossip"
    }
   ]
  },
  {
   "title": "UTXO Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "increase(lux_X_vm_lux_utxo_cache_hit{instance=~\"$host\"}[5m])/(increase(lux_X_vm_lux_utxo_cache_hit{instance=~\"$host\"}[5m])+increase(lux_X_vm_lux_utxo_cache_miss{instance=~\"$host\"}[5m]))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Unprocessed Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lux_X_handler_unprocessed_msgs_len{instance=~\"$host\"}",
     "legendFormat": "Pending Messages"
    }
   ]
  },
  {
   "title": "Incoming Messages Expired in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(lux_X_handler_expired{instance=~\"$host\"}[1m])",
     "legendFormat": "Expired"
    }
   ]
  }
 ]
}