name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run static analysis tests
        shell: bash
        run: scripts/lint.sh

      - name: Run shellcheck
        shell: bash
        run: scripts/shellcheck.sh